Sns pressure
Hyp-ed/hyped-2022 pull request #102
Opened 2022-01-22 15:59 UTC by rachel275

## Description
Code for the pressure sensor and updates to relevant files

2022-01-22 16:01 UTC, rachel275 commented
I have tried several times to fix the data.hpp and data.cpp and stop them deleting all the lines and re-adding them but I can't get it to reverse that, if anyone has any advice that would be great!

2022-01-24 21:24 UTC, amadrafi commented on src/data/data.hpp
> +      kPreCalibrating,
is there a purpose for the gap?

2022-01-24 23:35 UTC, MiltFra requested changes

2022-01-24 23:35 UTC, MiltFra commented on src/data/data.cpp
> +void Data::setPressure(const int &pressure)
Pretty sure this should just be in the general sensors data, no? We don't really want to do single reads all the time.
Also, try to be specific with the types here. `int` may mean different things on different machines, especially since we're compiling this on the BBB, too.

2022-01-24 23:35 UTC, MiltFra commented on src/data/data.cpp
> +void Data::setPressure(const int &pressure)
Also, I appreciate the references, but for an int it's excessive. In fact, the reference (if thought of as a pointer) may be exactly the same or even larger than `int`. For larger objects or those, you don't want to copy this is the right thing to do tho.

2022-01-24 23:35 UTC, MiltFra commented on src/data/data.hpp
> +
Add below here with the imu and encoder data.

2022-01-24 23:35 UTC, MiltFra commented on src/data/data.hpp
>    int temperature_;  // In degrees C
While you're at it, I'd move this into the data struct as well.

2022-01-24 23:35 UTC, MiltFra commented on src/sensors/interface.hpp
> +using data::PressureData;
Consider me angry. The right thing would've been to remove all the other `using` statements here.

2022-01-24 23:35 UTC, MiltFra commented on src/sensors/pressure.cpp
> +  double pressure = (static_cast<double>(raw_value) / 4095) * 5;
The types here seem mega funky. Firstly, I think we're mainly using float as our floating-point number type. Secondly, why convert it back to `int` if we can just keep it as a float? This value will not be used by any output, so I don't see any advantage of doing this.

2022-01-24 23:35 UTC, MiltFra commented on src/sensors/pressure.cpp
> +using utils::io::ADC;
bad.

2022-01-24 23:35 UTC, MiltFra commented on src/sensors/pressure.cpp
> +namespace hyped {
Please use `namespace hyped::sensors`

2022-01-24 23:35 UTC, MiltFra commented on src/sensors/pressure.cpp
> +  ADC thepin(pin_);
Are we sure that the pressure sensor uses ADC? or is this just based on old code?

2022-01-24 23:35 UTC, MiltFra commented on src/sensors/pressure.cpp
> +Pressure::Pressure(utils::Logger &log, int pin) : pin_(pin), log_(log)
I reckon pins should be `uint8_t`. Not sure, but any higher than that doesn't make any sense, right?

2022-01-24 23:35 UTC, MiltFra commented on src/sensors/pressure.hpp
> +  ~Pressure() {}
Leave out empty deconstructors. This is implied.

2022-01-24 23:36 UTC, MiltFra commented
On another note, I'd like to see a fake implementation of this. You may want to wait for #98 though.

2022-01-26 18:20 UTC, amadrafi approved these changes
Didn't come across any glaring errors.

2022-01-27 11:20 UTC, sashank17 reviewed
Did not find any errors apart from the ones already mentioned.
Also the using statements can be removed from most of the files I think.

2022-01-27 18:52 UTC, kshxtij commented on src/sensors/pressure.cpp
> +  ADC thepin(pin_);
This should be right, but i'll confirm after having a look at the datasheet.

2022-01-29 17:50 UTC, MiltFra commented on src/data/data.cpp
> +  const DataPoint<std::array<EncoderData, Sensors::kNumEncoders>> &encoder)  // NOLINT
Remove the NOLINTs please. Make sure to re-format after.

2022-01-29 17:52 UTC, MiltFra commented on src/sensors/pressure.hpp
> +   * @brief scale raw difital data to output in ms??
What does this even mean?

2022-01-29 17:55 UTC, MiltFra commented on src/sensors/pressure.cpp
> +  double pressure = (raw_value) / 4095 * 5;
This seems wrong. RHS is `int` or `uint8_t` (I'm genuinely not sure.) and the LHS is `double`. Surely we want `const float pressure = static_cast<double>(raw_value) / 819.0;` Please verify these numbers by the way.

2022-01-29 17:58 UTC, MiltFra requested changes
You broke some files by removing the `using namespace hyped::data

2022-01-29 17:58 UTC, MiltFra commented on src/sensors/interface.hpp
> -using data::ImuData;
This breaks compilation in several places. Please add explicit namespaces there.

2022-02-02 12:57 UTC, sashank17 approved these changes
Looks good to me

2022-02-03 12:15 UTC, MiltFra commented on src/data/data.hpp
> +  Lock lock_pressure_;
This is no longer required, is it?

2022-02-03 12:18 UTC, MiltFra commented on src/sensors/main.cpp
> +    checkTemperature();
We can still check this only every 20 iterations, right? Just make sure to only read/write the sensors data struct ONCE per iteration.

2022-02-03 12:18 UTC, MiltFra commented on src/sensors/pressure.cpp
> +  double P4       = (float(coefficients_[3]) / 1024l) * (float(delta_temp) / 2048L);
funky float vs double things are going on here. also use `static_cast<float>(x)` instead of `(float) x` or that horrible Python syntax I shall not repeat

2022-02-03 12:19 UTC, MiltFra commented on src/sensors/pressure.hpp
> +  Pressure(utils::Logger &log, int pressure_pin, int temp_pin);
types aren't specific enough once again

2022-02-04 17:06 UTC, MiltFra requested changes

2022-02-04 17:06 UTC, MiltFra commented on src/sensors/main.cpp
> +    iteration_count++;
`++iteration_count`

2022-02-04 17:06 UTC, MiltFra commented on src/sensors/main.cpp
> +  int iteration_count;
I mean this will technically work, but for more deterministic behaviour we should initialise this to zero.

2022-02-04 17:06 UTC, MiltFra commented on src/sensors/main.hpp
> +   *
Blank line?

2022-02-04 17:06 UTC, MiltFra commented on src/sensors/pressure.cpp
> +  int pressure = static_cast<int>((P1 + P2 - P3 - P4) / 100);
In `data`, pressure is a `uint32_t`. Why is it `int` here?

2022-02-04 17:06 UTC, MiltFra commented on src/sensors/main.cpp
> +  int iteration_count;
Also, make this `std::size_t` while you're at it.

2022-02-20 16:01 UTC, MiltFra requested changes

2022-02-20 16:01 UTC, MiltFra commented on src/sensors/pressure.cpp
> +Pressure::Pressure(hyped::utils::Logger &log, uint16_t pressure_pin, uint16_t temp_pin)
You shouldn't be passing loggers around like that anymore. Have a look at how other classes do it now. We want the identifier to be "PRESSURE" by the way.

2022-02-23 18:25 UTC, rachel275 commented on src/sensors/pressure.cpp
> +Pressure::Pressure(hyped::utils::Logger &log, uint16_t pressure_pin, uint16_t temp_pin)
Which identifier do we want to be "PRESSURE" here? I can't see any upper caps identifiers in other classes.

2022-02-23 18:25 UTC, rachel275 commented on src/sensors/pressure.cpp
> +Pressure::Pressure(hyped::utils::Logger &log, uint16_t pressure_pin, uint16_t temp_pin)
@MiltFra

2022-02-24 12:22 UTC, MiltFra commented on src/sensors/pressure.cpp
> +Pressure::Pressure(hyped::utils::Logger &log, uint16_t pressure_pin, uint16_t temp_pin)
https://github.com/Hyp-ed/hyped-2022/blob/728a67304310c27de8701dc72d2b0906fa7df40e/src/sensors/main.cpp#L18

2022-02-24 12:23 UTC, MiltFra commented on src/sensors/pressure.cpp
>        log_(log)
You probably want to make a new logger here.

2022-03-02 23:58 UTC, kshxtij approved these changes

2022-03-03 15:41 UTC, MiltFra approved these changes

2022-03-07 14:30 UTC, merged