Added critical failure for over temp/current
Hyp-ed/hyped-2022 pull request #103
Opened 2022-01-23 21:07 UTC by TomLonergan03

## Description
Adding critical failures for when motors are over maximum temperature or current

2022-01-23 22:42 UTC, MiltFra requested changes

2022-01-23 22:42 UTC, MiltFra commented on src/propulsion/rpm_regulator.hpp
>     * @param actual_temperature - max temperature out of all the motors
Please fix the comments.

2022-01-23 22:42 UTC, MiltFra commented on src/propulsion/state_processor.hpp
> +  bool isOverlimits();
Don't like this name. If anything, it should be `isOverLimits`.

2022-01-23 22:42 UTC, MiltFra commented on src/propulsion/state_processor.hpp
> +  static constexpr int kMaximumCurrent     = 1500;  // mA
Where are these values coming from? I think we should put them in `data::Data` to be honest.

2022-01-23 22:54 UTC, TomLonergan03 commented on src/propulsion/state_processor.hpp
> +  static constexpr int kMaximumCurrent     = 1500;  // mA
This is just moving them from rpm_regulator.hpp where they used to be. I don't know the origin of the values. I'll check the values with propulsion and move them

2022-01-26 20:48 UTC, MiltFra commented on src/data/data.hpp
> +  static constexpr int kMaximumCurrent     = 1500;  // mA
is `int` the right type here? I usually prefer explicit sizes as otherwise the behaviour may change based on machines.

2022-01-26 21:00 UTC, MiltFra commented on src/data/data.hpp
> +  static constexpr int kNumMotors          = 4;
formatting

2022-01-26 21:20 UTC, MiltFra approved these changes

2022-01-27 11:21 UTC, maryk-123 approved these changes

2022-01-27 12:27 UTC, merged