Arduino code for IR sensor on Lateral Suspension
Hyp-ed/hyped-2022 pull request #107
Opened 2022-01-27 18:52 UTC by supermegho

## Description
This is the initial Arduino code for counting the wheel revolutions on a lateral suspension wheel. A signal is sent to the BBB every time an input is received by one the IR pins.

 *Click up link* [](<link here>)

## Changes
- IR sensor pin takes an input
- Output is sent to BBB.

## Additional Info 
screenshots, commands to run etc.

2022-01-28 07:50 UTC, MiltFra requested changes
This just passes on the signals, right? I'd like to see the counting implemented before we pass this on. @kshxtij

2022-01-28 07:50 UTC, MiltFra commented on arduino/irsensor.cpp
> +    }
This is missing a closing bracket, no?

2022-01-28 07:50 UTC, MiltFra commented on arduino/irsensor.cpp
> +    pinMode (Output3, OUTPUT);
Formatting. `pinMode(Output3, OUTPUT);`

2022-01-28 07:50 UTC, MiltFra commented on arduino/irsensor.cpp
> +    if (statusSensor1 == 1){
No need to check the `== 1`. Just do `if (statusSensor1) { ... }`. Looks more intuitive, I think.

2022-02-03 18:18 UTC, supermegho commented on arduino/irsensor.cpp
> +    }
Yes, you are correct

2022-02-27 22:01 UTC, SnickeyX commented
@kshxtij and I spent some time trying to get the arduino to work. Most things failed, the strings method works for now; so committing this while we keep experimenting.

2022-03-03 00:14 UTC, kshxtij commented
Replaced by #120.

2022-03-03 00:14 UTC, closed without merging