MTC Warning message fix
Hyp-ed/hyped-2022 pull request #108
Opened 2022-01-30 18:36 UTC by TomLonergan03

## Description
Changed warning message system to be able to handle multiple errors

2022-01-30 18:37 UTC, TomLonergan03 commented on src/propulsion/controller.cpp
> +      }
This formatting makes me sad but the auto formatting keeps returning it to this

2022-01-30 18:38 UTC, TomLonergan03 commented on src/propulsion/controller.cpp
> +        = stoi(std::to_string(message.data[5]) + std::to_string(message.data[4])); // Merge error bytes into one string
This feels kinda hacky for concatenating bytes but seems to be the best way to do it

2022-02-01 10:13 UTC, MiltFra requested changes

2022-02-01 10:13 UTC, MiltFra commented on src/propulsion/controller.cpp
> +        log_.ERR("MOTOR", "Controller %d warning: Stall protection active");
You're missing an argument for `%d` here.

2022-02-03 18:21 UTC, MiltFra approved these changes

2022-02-05 17:20 UTC, adenhaus commented on src/propulsion/controller.cpp
> +      uint16_t warning_message = (message.data[5] << 8) + message.data[4];
const?

2022-02-07 00:58 UTC, kshxtij approved these changes
LGTM

2022-02-07 14:20 UTC, merged