Nav: navigation.cpp/hpp testing
Hyp-ed/hyped-2022 pull request #110
Opened 2022-02-07 14:32 UTC by callumTM

## Description
Testing for `navigation.cpp/hpp`, currently being used to try and understand the system better

2022-02-07 17:12 UTC, maxguy2001 commented on test/navigation/navigation.test.cpp
> +  std::cout << data_.getNavigationData().velocity
semicolon at the end of this line?

2022-02-07 17:19 UTC, maxguy2001 commented on test/navigation/navigation.test.cpp
> +#include "gtest/gtest.h"
'#include <gtest/gtest.h>'?

2022-02-07 18:17 UTC, MiltFra commented on test/navigation/navigation.test.cpp
> +#include "gtest/gtest.h"
This *may* not be an issue but it is highly advised as it's part of a different binary (to some degree, let's not get into the details of this). Essentially these headers are clearly not local to the source file.

2022-02-09 08:51 UTC, MiltFra requested changes

2022-02-09 08:51 UTC, MiltFra commented on test/navigation/navigation.test.cpp
> +  Sensors sensors_data_;
Why the underscore here? It's a local variable.

2022-02-09 08:51 UTC, MiltFra commented on test/navigation/navigation.test.cpp
> +  Randomiser::randomiseSensorsData(sensors_data_);
This is fine, don't worry.

2022-02-09 08:51 UTC, MiltFra commented on test/navigation/navigation.test.cpp
> +  // this should read the sensors data and use it to update velocity etc. but doesn't seem to
Have you checked what the randomiser actually writes into data? Maybe the values are such that we would deterministically expect a certain velocity?

2022-02-09 08:52 UTC, MiltFra commented on test/navigation/navigation.test.cpp
> +  // this should read the sensors data and use it to update velocity etc. but doesn't seem to
That's why you should put in hand-picked values because you know what to expect, by the way.

2022-04-02 12:09 UTC, closed without merging