Debug binary
Hyp-ed/hyped-2022 pull request #112
Opened 2022-02-12 19:01 UTC by MiltFra

2022-02-12 19:59 UTC, weijuinlee approved these changes
Looks alright.

2022-03-30 12:46 UTC, maxguy2001 requested changes

2022-03-30 12:46 UTC, maxguy2001 commented on src/debugging/observer.cpp
> +  uint32_t i = 0;
if you're only counting to 16 then `uint8_t` or `size_t`?

2022-03-30 12:46 UTC, maxguy2001 commented on src/debugging/observer.hpp
> +  static constexpr uint32_t kSleepTimeMillis = 10;
`uint8_t`?

2022-03-30 12:46 UTC, maxguy2001 commented on src/debugging/repl.cpp
> +void Repl::addShutdownCommand()
const?

2022-03-30 12:46 UTC, maxguy2001 commented on src/navigation/navigation.cpp
>    log_counter_++;
`++log_counter_`

2022-03-30 12:46 UTC, maxguy2001 commented on src/sensors/bms.hpp
>  constexpr uint32_t kFreq   = 4;             // in Hz
`static` and either `uint8_t` or `size_t`?

2022-03-30 12:46 UTC, maxguy2001 commented on src/sensors/bms_manager.cpp
>      if (battery.average_temperature < 0
`battery.average_temerature` has type `uint8_t` so can't be <0.

2022-03-30 16:10 UTC, maxguy2001 requested changes

2022-03-30 17:16 UTC, MiltFra commented on src/brakes/brake.cpp
> +void Brake::retract()
Where?

```
const void Brake::retract() // pointless
void Brake::retract() const // doesn't work 
```

or do you mean line 12? Then that doesn't work because we're reading I/O, I believe?

2022-03-30 17:17 UTC, MiltFra commented on src/brakes/brake.cpp
> +void Brake::engage()
nope. we change the state of the brake, do we not? even log messages aren't const because we need to lock `std::cout`.

2022-03-30 17:18 UTC, MiltFra commented on src/brakes/brake.cpp
> +bool Brake::isEngaged()
...

2022-03-30 17:19 UTC, MiltFra commented on src/data/data.hpp
> +  static constexpr size_t kNumMotors           = 4;
no because we index into an array with it. values smaller than 32-bits don't make much sense anyways; we'll chat about it.

2022-03-30 17:20 UTC, MiltFra commented on src/debugging/observer.hpp
> +  static constexpr uint32_t kSleepTimeMillis = 10;
it's a time, so actually this should be `uint64_t`.

2022-03-30 17:20 UTC, MiltFra commented on src/debugging/observer.cpp
> +  uint32_t i = 0;
no

2022-03-30 17:20 UTC, MiltFra commented on src/debugging/repl.cpp
> +void Repl::addShutdownCommand()
no, we're adding to `commands_`

2022-03-30 17:21 UTC, MiltFra commented on src/sensors/bms.hpp
>  constexpr uint32_t kFreq   = 4;             // in Hz
I'm not sure? Will check whether it's used outside. Will investigate the type.

2022-03-30 17:22 UTC, MiltFra commented on src/utils/concurrent/thread.cpp
> +void Thread::stop()
no :joy:

2022-03-30 18:13 UTC, maxguy2001 commented on configurations/config.json
> -    "keyence_pins": [67, 68],
Fair enough

2022-03-30 19:44 UTC, MiltFra commented on src/sensors/bms.hpp
>  constexpr uint32_t kFreq   = 4;             // in Hz
Making these static doesn't make any sense because they're not class members and not in a source file.

2022-03-30 19:46 UTC, MiltFra commented on src/sensors/bms.hpp
>  constexpr uint32_t kFreq   = 4;             // in Hz
Type is fine because it's passed to sleep which wants a `uint32_t`. I'd do it differently but this is not important enough.

2022-03-30 19:48 UTC, MiltFra commented on src/sensors/bms_manager.cpp
>      if (battery.average_temperature < 0
fake news https://github.com/Hyp-ed/hyped-2022/blob/a38e316f44681f241f7dff2f3424decf39219bf7/src/data/data.hpp#L82

2022-04-01 16:40 UTC, rachel275 approved these changes

2022-04-02 02:28 UTC, kshxtij approved these changes

2022-04-02 08:02 UTC, arjunnaha approved these changes

2022-04-02 20:15 UTC, maxguy2001 requested changes

2022-04-02 20:15 UTC, maxguy2001 commented on test/utils/integrator.test.cpp
>    float expected_value = max_time * max_time / 2;
const?

2022-04-02 20:15 UTC, maxguy2001 commented on test/utils/integrator.test.cpp
> +  int max_time                       = 100;
const?

2022-04-02 20:15 UTC, maxguy2001 commented on test/utils/integrator.test.cpp
>    for (t = data_time.begin(); t != data_time.end(); t++) {
?

2022-04-02 20:15 UTC, maxguy2001 commented on test/utils/kalman_multivariate.test.cpp
>    unsigned int k = 1;
?

2022-04-02 20:16 UTC, maxguy2001 commented on src/utils/io/spi.cpp
> +void Spi::write(uint8_t addr, uint8_t *tx, uint16_t len)
?

2022-04-02 20:16 UTC, maxguy2001 commented on src/utils/math/kalman_multivariate.hpp
>  namespace math {
?

2022-04-02 20:16 UTC, maxguy2001 commented on test/state_machine/transitions.test.cpp
> +  for (int i = kNoEmergencyFirst; i <= kLast; ++i) {
?

2022-04-02 20:16 UTC, maxguy2001 commented on test/state_machine/transitions.test.cpp
> +  for (int i = kNoEmergencyFirst; i <= kLast; ++i) {
?

2022-04-02 20:17 UTC, maxguy2001 commented on test/state_machine/transitions.test.cpp
> +  for (int i = kNoEmergencyFirst; i <= kLast; ++i) {
?

2022-04-02 20:17 UTC, maxguy2001 commented on test/state_machine/transitions.test.cpp
> +  for (int i = kNoEmergencyFirst; i <= kLast; ++i) {
?

2022-04-02 20:17 UTC, maxguy2001 commented on test/state_machine/transitions.test.cpp
> +  for (int i = kInitFirst; i <= kLast; ++i) {
?

2022-04-02 20:17 UTC, maxguy2001 commented on test/state_machine/transitions.test.cpp
>      for (int j = kInitFirst; j <= kLast; j++) {
?

2022-04-02 20:17 UTC, maxguy2001 commented on test/state_machine/transitions.test.cpp
>      for (int j = kInitFirst; j <= kLast; j++) {
?

2022-04-02 20:17 UTC, maxguy2001 commented on test/utils/kalman_multivariate.test.cpp
>    unsigned int k = 1;
?

2022-04-02 20:20 UTC, MiltFra commented on configurations/debugging/config.json
> +    "maximum_acceleration": 1000.0,
This could be any positive value whatsoever. In fact, now that I think about it, it's good that it's high so it will be incredibly obvious that something is wrong if the fake system is being used.

2022-04-02 20:22 UTC, MiltFra commented on src/brakes/main.cpp
> +      case data::State::kFailureBraking:
`hyped::brakes::Main::engage()` handles the checks internally. I shall rename it to make it clear.

2022-04-02 20:33 UTC, MiltFra commented on src/data/data.hpp
> +  uint16_t voltage;            // dV
Checked the datahsheet. Apparently the voltage cannot drop below 0.8 V.

2022-04-02 20:49 UTC, MiltFra commented on src/sensors/ambient_pressure.cpp
>    if (offset_at_actual_temperature < -17179344900 || offset_at_actual_temperature > 25769410560) {
just straight from the datasheet.

2022-04-02 21:09 UTC, MiltFra commented on src/utils/io/gpio.hpp
>    int fd_;                    // file pointer to /sys/class/gpio/gpioXX/value
No, file descriptors are `int`. Read https://linux.die.net/man/2/open

2022-04-02 21:11 UTC, MiltFra commented on src/utils/io/spi.cpp
> +void Spi::write(uint8_t addr, uint8_t *tx, uint16_t len)
Again, I believe you are right. But let this dragon sleep for now.

2022-04-02 21:13 UTC, MiltFra commented on test/state_machine/transitions.test.cpp
> +  for (int i = kNoEmergencyFirst; i <= kLast; ++i) {
No, because we're not indexing with this but casting it to `data::ModuleStatus`. Thus `int` should be fine.

2022-04-02 21:14 UTC, MiltFra commented on test/state_machine/transitions.test.cpp
>      for (int j = kInitFirst; j <= kLast; j++) {
`++j`, agreed. See above for `size_t`.

2022-04-02 21:20 UTC, maxguy2001 approved these changes
all good!

2022-04-02 21:22 UTC, merged