Refactored outlier detection function
Hyp-ed/hyped-2022 pull request #116
Opened 2022-02-13 03:10 UTC by maxguy2001

Refactored outlier detection function to clean up code and remove all references to "tukeyFences" to clarify functionality.

2022-02-14 08:22 UTC, MiltFra commented on src/navigation/navigation.cpp
> +  const auto iqr         = std::min(q3 - q1, kMinIQRBound);
Please explain.

2022-02-14 16:26 UTC, MiltFra commented on src/navigation/navigation.cpp
> +  const auto iqr         = std::min(q3 - q1, kMinIQRBound);
Two things: (a) you should absolutely rename it to something involving max or upper because the value on the left cannot be greater. (b) I don't like the usage of the abbreviation IQR (here and elsewhere). I think it stands for intermediate quartile ranges but I am not sure, really. This is a sign that maybe we should rename it.

2022-02-14 16:29 UTC, MiltFra commented on src/navigation/navigation.cpp
> +  data::nav_t q1, q2, q3;
Actually, this should probably be `std::array<data::nav_t, 3> quartile_bounds`. Now that I think about it (you see, this is all very WIP), why don't we create a function, e.g. `calculate_imu_quartile_bounds`, that takes the IMU readings and a mask and returns the quartiles? We could then unit test it right away.

2022-02-20 15:47 UTC, MiltFra commented on src/navigation/navigation.hpp
> +  std::array<data::nav_t, 3> quartile_bounds;
Two issues with this. (a) the naming is wrong again which lead me to search for the local declaration and (b) making this a class member is spaghetti code. Declare it locally in `calculateImuQuartiles` and then return it (you know, functions can have return types other than `void`). Then you can do `const auto quartile_bound = calculateImuQuartiles(...)` in the outlier detection method.

2022-02-20 15:47 UTC, MiltFra commented on src/navigation/navigation.hpp
> +  static constexpr data::nav_t kIqrScaler             = 1;  // 0.75
There is an IQR again...

2022-02-28 16:14 UTC, MiltFra commented on src/navigation/navigation.cpp
> +    status_ = data::ModuleStatus::kCriticalFailure;
I think we should write to `data` here right away.

2022-03-12 20:53 UTC, MiltFra requested changes
Overall pretty good stuff; some polishing still required, though.

2022-03-12 20:53 UTC, MiltFra commented on src/navigation/navigation.cpp
> +  (raw_acceleration_moving, kInterQuartileScaler);
This looks wrong.

2022-03-12 20:53 UTC, MiltFra commented on src/navigation/navigation.cpp
> +  std::array<data::nav_t, 3> quartile_bounds;
Move this down to be closer to its first use.

2022-03-12 20:53 UTC, MiltFra commented on src/utils/io/spi.cpp
> +}  // namespace hyped
something is off...

2022-03-12 20:53 UTC, MiltFra commented on src/navigation/navigation.hpp
> +  static constexpr data::nav_t kInterQuartileScaler   = 1;  // 0.75
confusing comment

2022-03-12 20:53 UTC, MiltFra commented on src/navigation/navigation.hpp
> +  using quartile_bounds          = std::array<data::nav_t, 3>;
Type naming...

2022-03-16 19:54 UTC, SnickeyX commented on src/utils/io/spi.cpp
> +}  // namespace hyped
this is still there

2022-03-23 19:04 UTC, MiltFra commented on src/navigation/navigation.cpp
> +    auto navigation_data          = data_.getNavigationData();
no it can't

2022-03-24 13:08 UTC, adenhaus approved these changes

2022-03-24 21:08 UTC, MiltFra commented on src/utils/io/spi.cpp
> +}  // namespace hyped
bump

2022-03-27 21:28 UTC, kshxtij approved these changes
Can be merged after the namespace comment is fixed.

2022-03-28 12:33 UTC, MiltFra approved these changes

2022-03-28 12:35 UTC, merged