Tel gui fix
Hyp-ed/hyped-2022 pull request #117
Opened 2022-02-13 12:48 UTC by adenhaus

Fixing issues that were affecting GUI compiling and running

2022-02-15 08:10 UTC, MiltFra commented on src/sensors/fake_batteries.cpp
> +      hp_success_{{35, 35, 35, 35, 35, 35, 35}},
@kshxtij can you please confirm that these values are sensible? They don't need to be perfect, just on the right order of magntitude.

2022-02-15 12:19 UTC, kshxtij commented on src/sensors/fake_batteries.cpp
> +      hp_success_{{35, 35, 35, 35, 35, 35, 35}},
- Voltage is measured in mV https://github.com/Hyp-ed/hyped-2022/blob/324e24d5fb310a19e7d04d7946038d03304e1017/src/sensors/bms.cpp#L135 so the hp_success value should be between 3300 and 4200 imo, rest looks right.

2022-02-15 14:59 UTC, MiltFra commented on src/sensors/fake_batteries.cpp
> +      hp_success_{{35, 35, 35, 35, 35, 35, 35}},
@adenhaus do those values do the trick? If not, we need to figure out what's going on.

2022-02-17 12:50 UTC, adenhaus commented on src/sensors/fake_batteries.cpp
> +      hp_success_{{35, 35, 35, 35, 35, 35, 35}},
@arjunnaha is the one working on this

2022-03-03 14:49 UTC, adenhaus commented on src/sensors/fake_batteries.cpp
> +      hp_success_{{35, 35, 35, 35, 35, 35, 35}},
@kshxtij when I change `hp_success` values to 3500 I get following errors:

`14:47:34.517 ERROR[BMS-MANAGER]: BMS HP 0 voltage out of range: 3500`
`14:47:34.517 ERROR[BMS-MANAGER]: battery failure detected`
`14:47:34.518 ERROR[STATE-MACHINE]: critical failure in batteries`

2022-03-03 14:56 UTC, adenhaus commented on src/sensors/fake_batteries.cpp
> +      hp_success_{{35, 35, 35, 35, 35, 35, 35}},
Okay @kshxtij says 35 is correct after all : )

2022-03-03 23:09 UTC, kshxtij approved these changes

2022-03-06 16:04 UTC, MiltFra requested changes
Just small things

2022-03-06 16:04 UTC, MiltFra commented on configurations/config.json
> +  "fake_trajectory": {
This config is intended for the run so please remove all references to the fake system here. We need to be able to catch faulty values and adding a bunch of nonsense isn't going to help with that.

2022-03-06 16:04 UTC, MiltFra commented on configurations/config.server.json
> +{"system":{"use_fake_brakes":false,"use_fake_high_power":false,"use_fake_temperature_fail":false,"use_fake_controller":false,"log_level":1,"use_fake_batteries":false,"use_fake_temperature":false,"use
This still needs to be removed after you've added it to the .gitignore.

2022-03-07 17:20 UTC, MiltFra approved these changes

2022-03-07 17:20 UTC, merged