Nav: wheel encoder code
Hyp-ed/hyped-2022 pull request #119
Opened 2022-02-28 20:05 UTC by maxguy2001

Draft PR of navigation system which deals with the wheel encoders.

2022-03-12 20:48 UTC, MiltFra requested changes

2022-03-12 20:48 UTC, MiltFra commented on src/data/data.hpp
> +  nav_t imu_displacement;                                 // m
I'm not a fan of this. How the navigation module comes up with a displacement value doesn't matter to the other modules, but there should be one definitive value. Don't leave the choice to everyone else. You can keep both values internally.

2022-03-12 20:48 UTC, MiltFra commented on src/navigation/navigation.cpp
> +  data::nav_t average         = sum / sizeof(encoder_data);
`encoder_data.size()`, I believe? `sizeof` returns the size of the object in bytes which I'm pretty sure is not what you want.

2022-03-12 20:48 UTC, MiltFra commented on src/navigation/navigation.cpp
> +    sum += encoder_data.at(i).value;
Explicit type conversions, please. Same below.

2022-03-12 20:48 UTC, MiltFra commented on src/navigation/navigation.cpp
> +  imu_acceleration_.timestamp = t;
It's not obvious to me what `t` is here (or rather where it comes from) which most likely means that something needs to change.

2022-03-12 20:48 UTC, MiltFra commented on src/navigation/navigation.cpp
> +  data::nav_t imu_displacement     = getImuDisplacement();
`const`

2022-03-12 20:48 UTC, MiltFra commented on src/navigation/navigation.cpp
> +    = static_cast<data::nav_t>(imu_displacement_.timestamp - previous_timestamp_) / 1000000.0;
`1e6` or something similar should work. Also, please leave a comment about the units (i.e. micros/us, millis/ms, nanos/ns, etc.) and possibly rename the variable to `time_delta_millis` or similar.

2022-03-12 20:48 UTC, MiltFra commented on src/telemetry/writer.cpp
> +  add("distance", 0.0, 1250.0, "m", nav_data.imu_displacement);
This is why we don't want two displacement values to be visible. The rest of the system is not designed for this.

2022-03-12 20:48 UTC, MiltFra commented on src/data/data.hpp
> +  nav_t imu_displacement;                                 // m
If you feel like we should be storing both for analysis purposes, you may want to add three fields, one of which is `displacement`. You can internally write the same value as `encoder_displacement`, but this would make this robust to future changes and not leave room for interpretation to other modules.

2022-03-12 20:48 UTC, MiltFra commented on test/randomiser.hpp
> +    nav_data.imu_displacement = static_cast<data::nav_t>((rand() % 1000 + 750) + randomDecimal());
Well, while you're at it, you should be adding the `wheel_encoder_displacement` randomisation here.

2022-03-14 11:53 UTC, maxguy2001 commented on test/randomiser.hpp
> +    nav_data.imu_displacement = static_cast<data::nav_t>((rand() % 1000 + 750) + randomDecimal());
Should I still do this given that it's not in the central data struct any more?

2022-03-14 19:16 UTC, maxguy2001 commented on src/navigation/navigation.cpp
> +  imu_acceleration_.timestamp = t;
It is assigned earlier as the timestamp of the sensors data and is then used to give the timestamp for our integrated estimates of velocity and displacement with the values received from sensors (hence the navigation estimate for the pod trajectory at that point in time) .

2022-03-14 22:47 UTC, MiltFra requested changes

2022-03-14 22:47 UTC, MiltFra commented on src/navigation/navigation.cpp
> +void Navigation::compareKeyenceImu()
Pretty sure this is not keyence.

2022-03-14 22:47 UTC, MiltFra commented on src/navigation/navigation.cpp
> +  initial_timestamp_              = utils::Timer::getTimeMicros();
I'd argue these should all be the same.

2022-03-16 13:37 UTC, maxguy2001 commented on src/navigation/navigation.cpp
> +  initial_timestamp_              = utils::Timer::getTimeMicros();
What should all be the same? Not sure what you're referring to.

2022-03-16 20:16 UTC, SnickeyX requested changes

2022-03-16 20:16 UTC, SnickeyX commented on src/utils/io/spi.cpp
> +}  // namespace hyped
namespace io very much teleported, I reckon this is a cmake moment

2022-03-16 20:16 UTC, SnickeyX commented on src/navigation/navigation.cpp
>  }
Might be on purpose but since velocity and acceleration values relating to the IMU are prefixed with ` imu_` , `imu_displacement_.value` would make more sense here.

2022-03-21 15:45 UTC, MiltFra commented on src/navigation/navigation.cpp
> +  initial_timestamp_              = utils::Timer::getTimeMicros();
there are separate calls to `utils::Time::getTimeMicros` which doesn't make much sense to me as all of those should get the same timestamp. In a sense it's arbitrary to take different ones.

2022-03-24 21:12 UTC, MiltFra requested changes

2022-03-24 21:12 UTC, MiltFra commented on src/navigation/navigation.cpp
> +  data::nav_t average         = sum / encoder_data.size();
`const`

2022-03-24 21:12 UTC, MiltFra commented on src/navigation/navigation.cpp
> +  if (std::abs(encoder_displacement - imu_displacement) > data::Navigation::kImuEncoderMaxErr) {
Why abbreviate to maxErr here?

2022-03-24 21:12 UTC, MiltFra commented on src/navigation/navigation.cpp
> +    = static_cast<data::nav_t>(imu_displacement_.timestamp - previous_timestamp_) / 1e6;
Are you sure about units here? I thought the timestamps were micros...

2022-03-24 21:12 UTC, MiltFra commented on src/navigation/navigation.cpp
>    log_counter_++;
`++log_counter;`

2022-03-25 12:53 UTC, adenhaus approved these changes

2022-03-26 20:36 UTC, MiltFra commented on src/navigation/navigation.cpp
> +    = static_cast<data::nav_t>(imu_displacement_.timestamp - previous_timestamp_) / 1e6;
Um... I don't think this is it. The two timestamps we're getting are micros and you're dividing by `1e6` so it should be seconds now, no? Also you should be careful about the units in the uncertainty, too, no?

2022-03-28 09:55 UTC, maxguy2001 commented on src/navigation/navigation.cpp
> +    = static_cast<data::nav_t>(imu_displacement_.timestamp - previous_timestamp_) / 1e6;
Wait if its already in micros don't we need to multiply by 1e6 to get seconds instead of dividing. Surely dividing by 1e6 would end up giving us pico seconds??

2022-03-28 12:18 UTC, kshxtij approved these changes

2022-03-28 12:38 UTC, MiltFra commented on src/navigation/navigation.cpp
> +    = static_cast<data::nav_t>(imu_displacement_.timestamp - previous_timestamp_) / 1e6;
What? :joy: I thought I was bad at calculations...

Say we have a time, e.g. 5 seconds. That's 5,000 miliseconds, 5,000,000 microseconds, 5,000,000,000 nanoseconds, ... you get the idea I hope?

2022-03-28 15:25 UTC, maxguy2001 commented on src/navigation/navigation.cpp
> +    = static_cast<data::nav_t>(imu_displacement_.timestamp - previous_timestamp_) / 1e6;
lucky I don't need to do any maths in my degree...

2022-04-02 21:29 UTC, MiltFra approved these changes

2022-04-04 16:05 UTC, arjunnaha reviewed
<img width="379" alt="image" src="https://user-images.githubusercontent.com/7504589/161585500-11138c47-4727-473c-979b-252ca4e0d651.png">
Why is this all being deleted?

Edit: Have you updated from master? Seems like lots of changes are being reverted

2022-04-04 17:21 UTC, arjunnaha approved these changes

2022-04-04 19:39 UTC, MiltFra requested changes
types

2022-04-04 19:39 UTC, MiltFra commented on src/navigation/navigation.cpp
> +  uint32_t current_trajectory_micros = imu_data.timestamp;
Is this not a timestamp? If so, `uint64_t`. Also, `const`, I believe.

2022-04-04 19:39 UTC, MiltFra commented on src/navigation/navigation.cpp
> +  if (std::abs(encoder_displacement - imu_displacement) > data::Navigation::kImuEncoderMaxError) {
Bit clunky. Maybe 
```cpp
const auto imu_encoder_error = std::abs(/* ... */);
// ...
```

2022-04-04 19:39 UTC, MiltFra commented on src/navigation/navigation.cpp
> +  data::nav_t initial_timestamp = utils::Timer::getTimeMicros();
Wrong type. Hint: If in doubt, use `auto`. Also, `const`.

2022-04-06 19:15 UTC, MiltFra approved these changes

2022-04-06 19:15 UTC, merged