Sns temperature interface
Hyp-ed/hyped-2022 pull request #132
Opened 2022-03-12 11:53 UTC by rachel275

## Description
Update temperature.c(h)pp. New conversion calculation added and general updates also made.

2022-03-24 14:14 UTC, maxguy2001 commented on src/sensors/temperature.cpp
> +  uint8_t temp = static_cast<int>((raw_value * kValues[0] / kValues[1]) * kValues[2]);
'static_cast<uint8_t>' ?

2022-03-24 14:36 UTC, maxguy2001 commented on src/sensors/main.cpp
> +  if (converted_pressure > 880 && !log_error_) {  // upper threshold is 900 is 880 as a safety
'converted_pressure' has type 'uint8_t which is always less than 880

2022-03-24 14:37 UTC, maxguy2001 commented on src/sensors/main.cpp
> +  if (converted_pressure < 560 && !log_error_) {
Same here. 'converted_pressure' is always less than 560.

2022-03-24 15:01 UTC, maxguy2001 commented on src/sensors/main.cpp
>    uint8_t converted_temperature = temperature_->getData();
will maybe have to change type for future if we are running on our test track in winter since 'converted_temperature' currently can't go below 0?

2022-03-24 15:07 UTC, maxguy2001 commented on src/sensors/fake_temperature.cpp
> +FakeTemperature::FakeTemperature(bool is_fail)
const

2022-03-24 15:08 UTC, maxguy2001 commented on src/sensors/fake_temperature.hpp
> +  FakeTemperature(bool is_fail);
const

2022-03-24 21:16 UTC, MiltFra requested changes
Most of this is done in #135 on the side. We shall leave this unmerged until we get there...

2022-03-31 20:44 UTC, MiltFra commented
In favour of #112

2022-03-31 20:44 UTC, closed without merging