SNS: I2C Interface
Hyp-ed/hyped-2022 pull request #137
Opened 2022-03-30 21:36 UTC by kshxtij

## Description

Implement I2C interface for Pressure Sensor.

2022-03-31 06:41 UTC, MiltFra requested changes
Overall quite good. Bit of style and a bit of usability, but that should be over quickly. Good job!

2022-03-31 06:41 UTC, MiltFra commented on src/utils/io/i2c.cpp
> +  if (sensor_addr_ != addr) setSensorAddress(addr);
`{ /* ... */ }`

2022-03-31 06:41 UTC, MiltFra commented on src/utils/io/i2c.cpp
> +void I2C::readData(const uint32_t addr, uint8_t *data, const uint8_t len)
This function currently has no way of reporting an error. Since we're going with the standard Unix style here, good practice would be to have it return an integer. Then negative means failure and you also get a confirmation of how many bytes were read.

2022-03-31 06:41 UTC, MiltFra commented on src/utils/io/i2c.cpp
> +  int ret = read(fd_, data, len);
the type of `read` is 

```cpp
ssize_t read(int fildes, void *buf, size_t nbyte)
```

the file descriptor and the data are fine, but `len` should be `size_t`. it's in line with what we're doing elsewhere, too.

also, ret should be `ssize_t`. to make your life easy, why not just use `const auto`?

2022-03-31 06:41 UTC, MiltFra commented on src/utils/io/i2c.cpp
> +  if (sensor_addr_ != addr) setSensorAddress(addr);
see above

2022-03-31 06:41 UTC, MiltFra commented on src/utils/io/i2c.cpp
> +  int ret = write(fd_, data, len);
see above

2022-03-31 06:41 UTC, MiltFra commented on src/utils/io/i2c.hpp
> +  void readData(uint32_t addr, uint8_t *data, uint8_t len);
`const` where possible

2022-03-31 06:41 UTC, MiltFra commented on src/utils/io/i2c.hpp
> +class I2C {
There is a philosophical question about the casing of digits here, but I read I2C as a single word so the class should be called `I2c`. This is being changed for ADC and GPIO and SPI in the debug binary PR.

2022-03-31 06:41 UTC, MiltFra commented on src/utils/io/i2c.hpp
> +  I2C();
Do we only have one I2C port? Otherwise, we may want to make it possible to choose one.

2022-03-31 06:41 UTC, MiltFra commented on src/utils/io/i2c.cpp
> +      fd_(0),
Given that you check leq 0 below, this should be -1. However, you don't need to initialise it at all as you're doing that in the body of the constructor.

2022-03-31 06:41 UTC, MiltFra commented on src/utils/io/i2c.cpp
> +  if (sensor_addr_ != addr) setSensorAddress(addr);
also, do we expect the same I2C instance to be used for different sensor addresses? otherwise, we could just restrict that and do the `ioctl` call on init?

2022-03-31 08:53 UTC, kshxtij commented on src/utils/io/i2c.cpp
> +  if (sensor_addr_ != addr) setSensorAddress(addr);
Yes because the call to get temperature and pressure would be 2 different sensor addressees even tho they are connected on the same bus. I know the wording is ambiguous but i followed the same naming convention as most online documentation about i2c.

2022-03-31 16:02 UTC, MiltFra commented on src/utils/io/i2c.cpp
> +  if (sensor_addr_ != addr) setSensorAddress(addr);
Would it then be a good idea to always call ioctl again? Or is that an expensive operation?

2022-03-31 16:54 UTC, kshxtij commented on src/utils/io/i2c.cpp
> +  if (sensor_addr_ != addr) setSensorAddress(addr);
Multiple i2c instances on the same bus would fail as you wouldn't be allowed to open the same file more than once while the process is running iirc. Also since we are passing in the bus manually, this would also be a common sense thing? as each bus can physically be only connected one sensor.

2022-03-31 18:25 UTC, MiltFra requested changes

2022-04-07 15:48 UTC, maxguy2001 commented on src/utils/io/i2c.cpp
> +void I2c::setSensorAddress(uint32_t address)
`const`?

2022-04-08 15:11 UTC, SnickeyX approved these changes

2022-04-13 00:05 UTC, MiltFra approved these changes

2022-04-13 00:06 UTC, merged