SNS: Brake Pressure
Hyp-ed/hyped-2022 pull request #138
Opened 2022-03-31 00:43 UTC by kshxtij

## Description

Implement Brake Pressure Sensor

TODO:

- [ ] Add IBrakePressure
- [ ] Implement BrakePressure
- [ ] Add brakePressurePinsFromFile
- [ ] Figure out scaling ~ Electronics pinged about this 
- [ ] Add Fake Brake Pressure 
- [ ] Add threshold checks/pressure decrease checks in main.cpp ~ Waiting for Electronics reply

2022-03-31 06:42 UTC, MiltFra commented on src/navigation/navigation.hpp
> +  using QuartileBounds           = std::array<data::nav_t, 3>;
yeah, @maxguy2001 didn't format properly once again...

2022-03-31 06:53 UTC, MiltFra requested changes
Good stuff. Quite a few things I would be pointing out if it weren't for the fact that I just approved a PR that contained basically the same code; so you're in luck and I shall fix my mistakes at another time.

2022-03-31 06:53 UTC, MiltFra commented on src/sensors/brake_pressure.cpp
> +  uint16_t raw_value = pin_.read();
`const`

2022-03-31 06:53 UTC, MiltFra commented on src/sensors/brake_pressure.hpp
> +   */
pointless comment

2022-03-31 06:53 UTC, MiltFra commented on src/sensors/brake_pressure.hpp
> +   */
pointless comment

2022-03-31 06:53 UTC, MiltFra commented on src/sensors/brake_pressure.hpp
> +  uint8_t getData() const override;
useless and faulty comment

2022-03-31 06:53 UTC, MiltFra commented on src/sensors/main.cpp
> +    log.error("Found %d keyence pins but %d were expected in configuration file at %s",
bit too much copy and paste here

2022-03-31 06:53 UTC, MiltFra commented on src/sensors/brake_pressure.cpp
> +  double pressure = static_cast<double>(raw_value) / 4095;
`const`; also just `float` is fine given that (a) navigation is using that and (b) we're casting to `int8_t` in a minute...

2022-04-03 09:51 UTC, MiltFra requested changes

2022-04-03 09:51 UTC, MiltFra commented on src/sensors/fake_brake_pressure.cpp
> +      if (is_fail_) failure_time_ = (rand() % 20 + 1) * 1000000;
`if (...) { ... }`

2022-04-03 09:51 UTC, MiltFra commented on src/sensors/fake_brake_pressure.cpp
> +    if (utils::Timer::getTimeMicros() - acc_start_time_ >= failure_time_) {
Here's how to improve control flow; this is more general advice, not specific to HYPED or even C++.
```cpp
if (!is_fail || failure_happened_) { 
  return; 
}
const auto time_elapsed = utils::Timer::getTimeMicros() - acc_start_time_;
if (time_elapsed >= failure_time_) { 
  // ...
}
```
Also note that I took out the `faiulre_time_ != 0` check because it doesn't do anything. If you want to be very precise you may initialise the field to `UINT64_MAX` (a.k.a. `^static_cast<uint64_t>(0)`).

Also, it is ironic to me that the only thing we ever use `utils::Timer` for is its static metho `getTimeMicros`... that's even though it has the capabilities of elapsing time like we need here as well... don't change it because it's too much work, just a note.

2022-04-03 09:51 UTC, MiltFra commented on src/sensors/main.cpp
> +      brake_pressures_[i] = std::move(brake_pressure);
`brake_pressures_.at(i) = std::make_unique<...>(...)`; no need to move.

2022-04-03 09:51 UTC, MiltFra commented on src/sensors/main.hpp
> +  std::array<data::BrakePressureData, data::Sensors::kNumBrakePressure> brake_pressure_data_;
Please sort these a bit. You can either group the sensors with their respective data or you can group data with data and sensors with sensors but then you need to maintain the same order in both blocks.

2022-04-03 20:33 UTC, MiltFra requested changes
Merge conflicts.

2022-04-10 12:17 UTC, SnickeyX requested changes

2022-04-10 12:21 UTC, MiltFra requested changes

2022-04-10 12:21 UTC, MiltFra commented on src/sensors/brake_pressure.hpp
> +  static uint16_t scaleData(uint8_t raw_value);
`const`

2022-04-10 12:21 UTC, MiltFra commented on src/sensors/main.cpp
> +      log_.info("Brake pressure (%u) exceeds minimum value (%d)", brake_pressure, 5600);
I know this is a bit late to point this out, but the wording in these comments has always bothered me... I just didn't know how else to phrase it! Can you do the following?
```cpp
log_.info("Brake pressure (%u) below minimum value (%u)", brake_pressure, 5600);
```
There are a couple of other places where we "exceed" a minimum value, I believe.

2022-04-10 12:21 UTC, MiltFra commented on src/sensors/main.cpp
> +std::optional<std::vector<uint8_t>> Main::brakePressurePinsFromFile(utils::Logger &log,
Can you add a quick test for this?

2022-04-10 12:21 UTC, MiltFra commented on src/sensors/main.hpp
> +  std::unique_ptr<ITemperature> temperature_;
I'm unsure as to what's going on here? This is about brake pressure right, why are we adding temperature sensors? Or am I misreading the diff somehow?

2022-04-10 12:31 UTC, kshxtij commented on src/sensors/main.cpp
> +std::optional<std::vector<uint8_t>> Main::brakePressurePinsFromFile(utils::Logger &log,
quick question, do we need a different sys_.config_.brake_pressure_config_path?

2022-04-10 15:27 UTC, MiltFra commented on src/sensors/main.cpp
> +std::optional<std::vector<uint8_t>> Main::brakePressurePinsFromFile(utils::Logger &log,
not sure? practically speaking we only have like two config files anyways so joining a couple of them shouldn't be an issue.

2022-04-11 13:43 UTC, SnickeyX approved these changes

2022-04-11 18:16 UTC, maxguy2001 requested changes

2022-04-11 18:16 UTC, maxguy2001 commented on src/data/data.hpp
> +  std::array<CounterData, kNumKeyence> keyence_stripe_counters;
keyence died :(

2022-04-11 18:16 UTC, maxguy2001 commented on src/sensors/brake_pressure.hpp
> +#include <cstdint>
remove?

2022-04-11 18:16 UTC, maxguy2001 commented on src/sensors/fake_brake_pressure.cpp
> +#include <stdlib.h>
is this used?

2022-04-13 00:04 UTC, MiltFra approved these changes

2022-04-13 00:04 UTC, merged