Nav: Wheel encoder outlier detection
Hyp-ed/hyped-2022 pull request #142
Opened 2022-04-07 15:18 UTC by maxguy2001

Outlier detection system for the wheel encoders. Based on the current system used for IMUs.

2022-04-07 15:28 UTC, adenhaus approved these changes

2022-04-08 15:19 UTC, SnickeyX requested changes

2022-04-08 15:19 UTC, SnickeyX commented on src/navigation/navigation.cpp
> +  if (imu_quartiles == true) {
you could just do `if(imu_quartiles)` here and if that's not intuitive then maybe change the parameter name (e.g `has_imu_quartiles`)

2022-04-08 15:30 UTC, SnickeyX requested changes

2022-04-08 15:30 UTC, SnickeyX commented on src/navigation/navigation.cpp
> +  } else if (imu_quartiles == false) {
an `else` should work here just fine since there are no other else if cases in the outer-most if-statement

2022-04-08 15:30 UTC, SnickeyX commented on src/navigation/navigation.cpp
> +    const auto exceeds_limits = data_array.at(i) < lower_limit || data_array.at(i) > upper_limit;
this could just be `const bool exceeds_limits`

2022-04-10 08:01 UTC, MiltFra requested changes

2022-04-10 08:01 UTC, MiltFra commented on src/navigation/navigation.cpp
> +                                              const data::nav_t threshold)
Lastly, why are we even doing this thing where we modify this data array? Would a more functional style not be better? I.e. take in "raw data", do calculations and raise errors as required, and then return an adjusted array. Would be more readable I believe.

2022-04-11 16:54 UTC, maxguy2001 commented on src/navigation/navigation.cpp
> +                                                          const bool get_imu_quartiles)
yeah I wasn't sure about sticking it all in 1 function but it just felt more contained, will switch to 2 functions

2022-04-11 17:28 UTC, arjunnaha approved these changes

2022-04-13 00:00 UTC, MiltFra requested changes

2022-04-13 00:00 UTC, MiltFra commented on src/navigation/navigation.cpp
> +  data::nav_t encoder_data_value = 0;
This is unused (surprised clang+Werror didn't catch this?). Also, I would restructure this as follows:
```cpp
const auto encoder_data = data_.getSensorsWheelEncoderData();

EncoderArray encoder_data_array;
uint32_t sum = 0;
for (size_t i = 0; i < encoder_data.size(); ++i) {
    sum += encoder_data.at(i).value;
    encoder_data_array.at(i) = encoder_data.at(i).value;
}
```
Alternatively,  if you're feeling fancy
```cpp
const auto encoder_data = data_.getSensorsWheelEncoderData();

EncoderArray encoder_data_array;
std::transform(encoder_data.begin(), encoder_data.end(), encoder_data_array.begin(),
               [](const auto &data) { return data.value; });
const auto sum = std::accumulate(encoder_data_array.begin(), encoder_data_array.end(), 0);
```

2022-04-13 00:00 UTC, MiltFra commented on src/navigation/navigation.hpp
> +  using EncoderArray             = std::array<data::nav_t, data::Sensors::kNumEncoders>;
shouldn't this be `uint32_t`?

2022-04-13 00:00 UTC, MiltFra commented on src/navigation/navigation.cpp
> +  std::array<data::nav_t, 3> quartile_bounds;
Move this further down towards its first use.

2022-04-13 00:00 UTC, MiltFra commented on src/navigation/navigation.cpp
> +  std::vector<data::nav_t> data_vector;
Again, this should be `uint32_t`, right?

2022-04-13 00:00 UTC, MiltFra commented on src/navigation/navigation.cpp
> +    log_.error("At least two Encoders no longer reliable, entering CriticalFailure.");
There clearly is an error here but we still return something without indicating to the caller that this is invalid. The return type of this function should be `std::optional<Navigation::QuartileBounds`; then you can return `std::nullopt` in the failure case.

2022-04-18 14:37 UTC, maxguy2001 commented on src/navigation/navigation.cpp
> +  data::nav_t encoder_data_value = 0;
I was not feeling fancy :(

2022-04-18 14:37 UTC, maxguy2001 commented on src/navigation/navigation.cpp
> +  data::nav_t encoder_data_value = 0;
I was not feeling fancy :(

2022-04-18 15:00 UTC, maxguy2001 commented on src/navigation/navigation.cpp
> +    log_.error("At least two Encoders no longer reliable, entering CriticalFailure.");
the same issue exists in the equivalent imu function by the looks of it but we've written the fail state directly to data so once this iteration of the `nav.navigate()` loop finishes, the main function will switch to failure state and the breaks will be activated so this function will basically be ignored while we brake?

2022-04-18 15:00 UTC, maxguy2001 commented on src/navigation/navigation.cpp
> +    log_.error("At least two Encoders no longer reliable, entering CriticalFailure.");
the same issue exists in the equivalent imu function by the looks of it but we've written the fail state directly to data so once this iteration of the `nav.navigate()` loop finishes, the main function will switch to failure state and the breaks will be activated so this function will basically be ignored while we brake?

2022-04-21 06:51 UTC, MiltFra approved these changes

2022-04-21 06:52 UTC, merged