SNS - Brake Pressure
Hyp-ed/hyped-2022 pull request #151
Opened 2022-05-26 21:50 UTC by SnickeyX

Added brake pressure tasks to observer + changed `can_listener.cpp` so c++20 methods are avoided

2022-05-27 16:18 UTC, MiltFra requested changes
only small things

2022-05-27 16:18 UTC, MiltFra commented on src/debugging/observer.cpp
> +
too much whitespace

2022-05-27 16:18 UTC, MiltFra commented on src/debugging/observer.cpp
> +    json_writer.Key("value");
indentation is off

2022-06-01 06:39 UTC, kshxtij approved these changes

2022-06-03 13:13 UTC, maxguy2001 approved these changes
looks fine

2022-06-12 17:52 UTC, MiltFra commented on src/debugging/observer.cpp
> +    json_writer.Key("value");
bump

2022-06-12 17:54 UTC, MiltFra approved these changes

2022-06-12 17:54 UTC, merged