Mtc rpm_regulator.[ch]pp cleanup
Hyp-ed/hyped-2022 pull request #44
Opened 2021-10-18 14:42 UTC by TomLonergan03

## Description
Correcting rpm_regulator.[ch]pp files to align to style guide
Changes `#includes` and function calls for rpm_regulator.[ch]pp in state_processor.[ch]pp to support these changes
## Changes
- Corrected file names
- Fixed variable names
- added `consts` where necessary
- Fixed class names
- Fixed type error in `calculateRpm`

2021-11-01 15:01 UTC, MiltFra commented on src/propulsion/rpm_regulator.cpp
> +  if (actual_current < kMaximumCurrent && actual_rpm == optimal_rpm
Bump @TomLonergan03

2021-11-01 15:27 UTC, TomLonergan03 commented on src/propulsion/rpm_regulator.cpp
> +  if (actual_current < kMaximumCurrent && actual_rpm == optimal_rpm
Whoops sorry I forgot about this
Should be sorted now I think

2021-11-01 15:52 UTC, MiltFra commented on src/propulsion/rpm_regulator.cpp
> +  return target;
`return std::max(target, 0);`

2021-11-01 23:25 UTC, MiltFra commented on src/propulsion/rpm_regulator.cpp
> +  return std::max(target,0);
pretty sure there's a space missing here... sorry :D

2021-11-02 10:57 UTC, MiltFra approved these changes

2021-11-04 22:58 UTC, suryanshmanocha requested changes
Minor nitpicks

2021-11-04 22:58 UTC, suryanshmanocha commented on src/propulsion/rpm_regulator.cpp
> +  return std::round(0.32047 * actual_velocity * actual_velocity + 297.72578 * actual_velocity
Sorry - I don't have much context here, but where are these number derived from? Generally 'magic numbers' are bad practise. I would store these as constant expressions instead IMO.

2021-11-04 22:58 UTC, suryanshmanocha commented on src/propulsion/rpm_regulator.cpp
> +  if (actual_rpm < optimal_rpm) { return std::round(optimal_rpm * 0.1); }
Ternery might be cleaner:
`return (actual_rpm < optimal_rpm) ? return std::round(optimal_rpm * 0.1) : std::round(optimal_rpm * -0.05);`

2021-11-05 09:01 UTC, MiltFra commented on src/propulsion/rpm_regulator.cpp
> +  return std::round(0.32047 * actual_velocity * actual_velocity + 297.72578 * actual_velocity
That's a very valid question, one that we found an answer for: through simulations, we determined the optimal frequencies for different velocities. To make this data usable, somebody fit a quadratic polynomial to those data points and this is the result. I agree though, there should at least be a comment. Please don't extract constants because this is going to change anyways - don't make it look more sophisticated than it is.

2021-11-05 09:09 UTC, MiltFra commented on src/propulsion/rpm_regulator.cpp
> +  if (actual_rpm < optimal_rpm) { return std::round(optimal_rpm * 0.1); }
Thanks for reminding me to ban the ternary operator in the new repo. Jokes aside, I'm not convinced this operator has ever led to anything good.

2021-11-06 15:33 UTC, suryanshmanocha commented on src/propulsion/rpm_regulator.cpp
> +  return std::round(0.32047 * actual_velocity * actual_velocity + 297.72578 * actual_velocity
What do you mean it's going to change ?
Should there not be a //TODO: in that case?

2021-11-06 15:38 UTC, suryanshmanocha commented on src/propulsion/rpm_regulator.cpp
> +  if (actual_rpm < optimal_rpm) { return std::round(optimal_rpm * 0.1); }
Fair enough - there seems to be quite some debate on whether they actually improve readability

2021-11-06 17:06 UTC, MiltFra commented on src/propulsion/rpm_regulator.cpp
> +  return std::round(0.32047 * actual_velocity * actual_velocity + 297.72578 * actual_velocity
The `// TODO` would be "figure out motor controllers" so I don't think there's any point in having it... Like, we have no clue what the final solution is going to look like so it doesn't matter too much.

2021-11-06 17:07 UTC, MiltFra commented on src/propulsion/rpm_regulator.cpp
> -                    + 1024.30824);
Try putting comments on the line above so you don't contribute to the line length, possibly exceeding it. It makes the auto-formatting more difficult.

2021-11-07 23:36 UTC, suryanshmanocha approved these changes

2021-11-08 11:14 UTC, merged