Nav kalman filter cleanup
Hyp-ed/hyped-2022 pull request #56
Opened 2021-10-21 14:30 UTC by maxguy2001

## Description
clean up `kalman_filter.cpp` and `kalman_filter.hpp` in navigation

## Changes
- Remove `using` to make typing clearer
- Changed increments to prefix notation
- Fixed naming to match style guide
- Add `const` for readability

2021-11-01 23:21 UTC, MiltFra commented on src/navigation/kalman_filter.cpp
>    ;
lonely `;`

2021-11-01 23:25 UTC, MiltFra requested changes

2021-11-01 23:25 UTC, MiltFra commented on src/navigation/kalman_filter.cpp
>  void KalmanFilter::updateStateTransitionMatrix(double dt)
`const`

2021-11-01 23:25 UTC, MiltFra commented on src/navigation/kalman_filter.cpp
>  void KalmanFilter::updateMeasurementCovarianceMatrix(double var)
`const`

2021-11-01 23:25 UTC, MiltFra commented on src/navigation/kalman_filter.cpp
>  void KalmanFilter::updateMeasurementCovarianceMatrix(double var)
also `data::nav_t`? why is this `double`?

2021-11-01 23:25 UTC, MiltFra commented on src/navigation/kalman_filter.cpp
> +const data::nav_t KalmanFilter::filter(data::nav_t z)
remove leading `const`, add `const` for `z`

2021-11-15 23:21 UTC, MiltFra commented on src/navigation/kalman_filter.cpp
> +void KalmanFilter::updateStateTransitionMatrix(const double dt)
`double`

2021-11-23 10:09 UTC, MiltFra approved these changes

2022-01-19 18:01 UTC, callumTM approved these changes
Looks all good to me!

2022-01-19 18:12 UTC, merged