NAV: IMU Data Logger Cleanup
Hyp-ed/hyped-2022 pull request #61
Opened 2021-10-21 21:06 UTC by callumTM

Cleans `imu_data_logger.cpp` and  `imu_data_logger.hpp`

## Changes
- Added `const`
- Removed `using`
- Fixed types
- Fixed variable names to adhere to Style Guide

2021-10-30 09:24 UTC, callumTM commented on src/navigation/imu_data_logger.cpp
> +  *outfile_ << raw_acceleration[0] << ",";
I believe we need to keep the order, however, I think we could do 3 for loops, each with 3 iterations i.e. one for raw acceleration, another for calibrated then the last for x?

2021-10-30 10:17 UTC, callumTM commented on src/navigation/imu_data_logger.hpp
>  class ImuDataLogger {
Is this required? I've not seen it in any of the other header files.

2021-11-01 03:42 UTC, suryanshmanocha commented on src/navigation/imu_data_logger.cpp
> +  *outfile_ << raw_acceleration[0] << ",";
That's what I meant, I think that would be better!

2021-11-01 03:50 UTC, suryanshmanocha commented on src/navigation/imu_data_logger.hpp
>  class ImuDataLogger {
I meant a brief docstring for the constructor - it should be at line 22, my bad.

2021-11-01 08:42 UTC, MiltFra commented on src/navigation/imu_data_logger.cpp
> +  *outfile_ << raw_acceleration[1] << ",";
Just noticed that this `ofstream` is still behind a pointer even though there's no reason for that.

2021-11-01 18:31 UTC, callumTM commented on src/navigation/imu_data_logger.cpp
> +  *outfile_ << raw_acceleration[1] << ",";
I'm not 100% sure what you mean. Could you clarify please?

2021-11-01 23:19 UTC, MiltFra commented on src/navigation/imu_data_logger.cpp
> +  *outfile_ << raw_acceleration[1] << ",";
It's declared as `std::ofstream *outfile_` but I think making it `std::ofstream outfile_` would be fine. There's no real reason to make this a pointer.

2021-11-01 23:20 UTC, MiltFra commented on src/navigation/imu_data_logger.cpp
> +  *outfile_ << raw_acceleration[1] << ",";
Then you can remove the arguments from the constructor altogether and call `outfile_.open(..)` instead of `outfile_->open(..)`.

2021-11-04 23:40 UTC, suryanshmanocha requested changes
Small thing only

2021-11-04 23:40 UTC, suryanshmanocha commented on src/navigation/imu_data_logger.cpp
> +  for (std::size_t i = 0; i < 3; i++) {
Sorry for going back and forth on this, maybe you can make an auxiliary function to help add commas to avoid code repetition?

So it'll look something like this:
`void ImuDataLogger::appendToFile(const data::NavigationVector &vector) {
  for (std::size_t i = 0; i < 3; i++) {
    outfile_ << vector[i] << ",";
}`

Then we just call:
 `appendToFile(raw_acceleration)
appendToFile(calibrated_acceleration)
appendToFile(x)
`

2021-11-05 08:57 UTC, MiltFra commented on src/navigation/imu_data_logger.cpp
> +  for (std::size_t i = 0; i < 3; i++) {
I'm not sure I agree on this to be honest. You're right, there's repetition here, but I think it's very clear what's happening. This is not a massive function in need of refactoring so I'm tempted to leave it like that.

2021-11-06 15:25 UTC, suryanshmanocha approved these changes

2021-11-06 17:05 UTC, MiltFra approved these changes

2021-11-06 17:05 UTC, merged