Update recvloop
Hyp-ed/hyped-2022 pull request #73
Opened 2021-10-25 09:35 UTC by dhb03

## Description
Give a brief summary of what this PR contributes 

 *Click up link* [](<link here>)

## Changes
- telem_data_struct shortened to telem_data

## Additional Info

2021-11-05 08:54 UTC, MiltFra requested changes

2021-11-05 08:54 UTC, MiltFra commented on src/telemetry/recvloop.cpp
> +}  // namespace telemetry
You removed a few too many braces. This is now closing the namespace. There is no way this compiled on your machine, by the way.

2021-11-05 08:54 UTC, MiltFra commented on src/telemetry/recvloop.cpp
> +
Now you've removed even more braces when you should've added some :D

2022-01-19 08:19 UTC, MiltFra approved these changes

2022-01-20 10:32 UTC, adenhaus approved these changes

2022-01-20 10:33 UTC, merged