GPIO Cleanup
Hyp-ed/hyped-2022 pull request #76
Opened 2021-10-28 21:12 UTC by kshxtij

## Description
Clean up of gpio_manager.cpp, gpio_manager.hpp, gpio_counter.cpp, gpio_counter.hpp.

Removed all references to using.

2021-10-30 12:37 UTC, MiltFra commented on src/sensors/gpio_manager.cpp
> +    hp_ssr_.emplace_back(new utils::io::GPIO(sys_.config->sensors.hp_shutoff[i], utils::io::gpio::kOut));
this should be `hp_ssr_.emplace_back(sys.config->sensors.hp_shutoff[i], utils::io::gpio::kOut)`. Note that `new` performs a heap allocation and returns a pointer. However, we want to construct the object in the memory that has been allocated for the vector already.

2021-10-31 14:49 UTC, MiltFra commented
Huh, seems like this still requires the copy constructor, didn't know that...

2021-11-04 23:31 UTC, suryanshmanocha requested changes

2021-11-04 23:31 UTC, suryanshmanocha commented on src/sensors/gpio_counter.hpp
>    GpioCounter(utils::Logger &log, int pin);
const int

2021-11-18 09:58 UTC, MiltFra commented on src/sensors/gpio_counter.hpp
>    GpioCounter(utils::Logger &log, int pin);
Not even sure `int` is the right type here...

2022-01-19 08:28 UTC, MiltFra commented
Closed in favour of #98.

2022-01-19 08:28 UTC, closed without merging