Modified safety ranges for the batteries according to the information on wiki
Hyp-ed/hyped-2022 pull request #77
Opened 2021-10-31 20:55 UTC by Davidhqm

## Changes
- change 1: LP safety ranges for temperature, voltage, and current 
- change 2: HP safety ranges for temperature, voltage, and current

2021-11-01 14:59 UTC, MiltFra requested changes

2021-11-01 15:07 UTC, kshxtij commented on src/sensors/bms_manager.cpp
> +        || battery.average_temperature > 80) {  // temperature in 0C to 80C
They said 80 degrees is the "shut-off" value where we should stop the pod instantly. They asked if we could implement a warning of some sort at 70 degrees, which i added to the to-do list.

2021-11-01 15:12 UTC, MiltFra commented on src/sensors/bms_manager.cpp
> +        || battery.average_temperature > 80) {  // temperature in 0C to 80C
Do it here and add a comment explaining the above. No need to delay. Same goes for all the other values. Make sure we don't lose how we got that information in the first place! (I.e. document the hard limits)

2021-11-04 18:44 UTC, kshxtij approved these changes

2021-11-05 08:50 UTC, MiltFra commented on src/sensors/bms_manager.cpp
> +        || battery.average_temperature > 70) {  // temperature in 0C to 70C (70C is the upper safe limit; 80 is the shutdown temperature)
please put the comment above the if to not exceed the line limit. auto format after; it should be nicer then

2021-11-07 02:50 UTC, MiltFra approved these changes
I fixed the formatting. The changes look fine to me now.

2021-11-18 09:55 UTC, merged