NAV: main_log.cpp/hpp Cleanup
Hyp-ed/hyped-2022 pull request #82
Opened 2021-11-02 00:09 UTC by callumTM

Cleans `main_log.cpp `and `main_log.hpp`

## Changes
- changed `int` to `std::size_t` for loops

2021-11-03 08:43 UTC, MiltFra requested changes

2021-11-03 08:43 UTC, MiltFra commented on src/navigation/main_log.cpp
>                "Update: g=(%.5f, %.5f, %.5f)",  // NOLINT
Remove the `// NOLINT`

2021-11-03 08:43 UTC, MiltFra commented on src/navigation/main_log.cpp
>      gravity_calibration_[j] = online_array[j].getMean();
Use `.at(i)` instead of `[i]`

2021-11-03 08:43 UTC, MiltFra commented on src/navigation/main_log.hpp
>    Logger &log_;
`utils::`

2021-11-03 08:43 UTC, MiltFra commented on src/navigation/main_log.hpp
>    explicit MainLog(uint8_t id, Logger &log);
This doens't agree with the cpp file.

2021-11-03 08:43 UTC, MiltFra commented on src/navigation/main_log.hpp
>  using data::ImuData;
lots of `using`

2021-11-06 23:45 UTC, callumTM commented on src/navigation/main_log.cpp
> +    log_.INFO("NAV", "Update: g=(%.5f, %.5f, %.5f)", gravity_calibration_.at(j)[0],
This can either be `gravity_calibration_.at(j)[0]` or what it was originally `gravity_calibration_[j][0]`. The first is clearer but the second is closer to the preferred style.

2021-11-06 23:48 UTC, callumTM commented on src/navigation/main_log.hpp
>    explicit MainLog(uint8_t id, Logger &log);
Should the log be described just as "System logger"?

2021-11-07 02:46 UTC, MiltFra commented on src/navigation/main_log.cpp
> +    log_.INFO("NAV", "Update: g=(%.5f, %.5f, %.5f)", gravity_calibration_.at(j)[0],
I prefer the former. In any case, I think we should provide functionality to log vectors more consistently.

2021-11-07 02:47 UTC, MiltFra commented on src/navigation/main_log.hpp
> +  explicit MainLog(uint8_t id, utils::Logger &log);
What I mean by disagreement is that this should be `explicit MainLog(const uint8_t id, utils::Logger &log)`; exactly as it is in the `.cpp` file.

2021-11-07 11:55 UTC, MiltFra commented on src/navigation/main_log.cpp
> +typedef std::array<data::ImuData, data::Sensors::kNumImus> ImuDataArray;
I'm not a fan of this `typedef` but for now you should convert it to a `using`:

```cpp
using ImuDataArray = std::array<data::ImuData, data::Sensors::kNumImus>;
```

This is considered better practice because it's more readable and has a few more features.

2021-11-07 11:55 UTC, MiltFra commented on src/navigation/main_log.cpp
> +        = sensor_readings.value.at(i).acc;  // TODO: .acc should be renamed to acceleration, but
This TODO should go on the line above because it's messing up the formatting.

2021-11-08 11:13 UTC, MiltFra approved these changes

2021-11-18 14:22 UTC, suryanshmanocha approved these changes

2021-11-18 16:00 UTC, weijuinlee reviewed
Looks alright to me and I agree with the use of scope resolution to avoid conflict.

2021-11-19 09:59 UTC, merged