started implementing additional and status data packing
Hyp-ed/hyped-2022 pull request #84
Opened 2021-11-04 14:43 UTC by adenhaus

## Description
Started implementing `packAdditionalData` and `packStatusData` in `writer.cpp`

## Additional Info 
Goal is to pack entire (relevant) central data structure from `data.hpp`. Maybe will combine `crucial`, `additional` and `status` data in the future but for now just getting it packed.

2021-11-08 11:12 UTC, MiltFra requested changes

2021-11-08 11:12 UTC, MiltFra commented on src/telemetry/writer.cpp
> +  for (int i = 0; i < batteries_data.kNumLPBatteries; i++) {
`++i`

2021-11-08 11:12 UTC, MiltFra commented on src/telemetry/writer.cpp
> +  for (int i = 0; i < batteries_data.kNumHPBatteries; i++) {
`std::size_t` instead of `int`

2021-11-08 11:12 UTC, MiltFra commented on src/telemetry/writer.cpp
> +  data::EmergencyBrakes brakes_data = data_.getEmergencyBrakesData();
I'd make this `const auto` instead of `data::EmergencyBrakes`

2021-11-08 11:12 UTC, MiltFra commented on src/telemetry/writer.cpp
> +    add("lp_battery_" + battery_num + "_volt", batteries_data.low_power_batteries[i].voltage);
can we not have a JSON array instead of putting the index in the key? Just structure it the same way as we do it in `data`.

2021-11-08 11:23 UTC, adenhaus commented on src/telemetry/writer.cpp
> +    add("lp_battery_" + battery_num + "_volt", batteries_data.low_power_batteries[i].voltage);
Not sure what you mean. In `data` it's just a struct? There's no `add` overload in `writer` that supports arrays right now, so I think every variable has to be added individually.

2021-11-09 08:33 UTC, MiltFra commented on src/telemetry/writer.cpp
> +    add("lp_battery_" + battery_num + "_volt", batteries_data.low_power_batteries[i].voltage);
I mean, the writer is part of our code so you can just add that functionality?

2021-11-09 08:34 UTC, MiltFra commented on src/telemetry/writer.cpp
> +  data::EmergencyBrakes brakes_data = data_.getEmergencyBrakesData();
all

2021-11-18 11:31 UTC, adenhaus commented on src/telemetry/writer.cpp
> +    add("lp_battery_" + battery_num + "_volt", batteries_data.low_power_batteries[i].voltage);
`batteries_data.high_power_batteries` and `batteries_data.low_power_batteries` are arrays of structs. RapidJSON does not support serialising structs, so it isn't an array issue, the struct has to be manually packed, and having the index tells us which battery it is anyway. https://github.com/Tencent/rapidjson/issues/1299

2021-11-19 09:58 UTC, MiltFra requested changes
Doesn't build because of GTest.

2021-11-22 09:40 UTC, MiltFra commented
Have you tried running this? I doubt this works.

2021-11-22 11:30 UTC, adenhaus commented
> Have you tried running this? I doubt this works. You'll have to call `json_writer_.StartObject` somewhere. Right now you're just adding the contents of the battery struct to the array consecutively, instead of adding separate JSON objects for each struct.

I'm pretty sure it would work because this is how the rest of the data points are being added. `StartObject` is called by `start` in `sendloop.cpp`, then all the `pack` functions are called, and inside them `add` is used to add stuff.

Anyway, I've rewritten it so that there is an `add` overload specifically for the `BatteryData` struct, so each one is its own `json` object. This approach doesn't really seem aligned to what the rest of the code is doing, because other structs don't really have their own `add` overloads, `add` is just used to add every one of their individual fields, which is what I was doing for `BatteryData` before. On the other hand, even though it's not how the others do it, this might be the best approach for `BatteryData` specifically because it's the only case where we have structs in a list.

Let me know what you think.

2021-11-23 09:53 UTC, MiltFra requested changes

2021-11-23 09:53 UTC, MiltFra commented on src/telemetry/writer.cpp
> +  const auto sensors_data   = data_.getSensorsData();
I don't see this being used. In fact, I like the structure above where you get one part of the CDS and pack it and then the next and so on. I'd stick to that.

2021-11-23 09:53 UTC, MiltFra commented on src/telemetry/writer.cpp
> +  const auto nav_data = data_.getNavigationData();
Try and be a bit more conservative with obtaining data. It's a relatively expensive operation and here you're just taking the module status. You may want to consider making functions

```cpp
void Writer::packNavigationData() {}
void Writer::packMotorsData() {}
/* ... */
```
You can then even pack each part into its own object, the way it's being done in the CDS.

2021-11-23 09:53 UTC, MiltFra commented on src/telemetry/writer.cpp
> +  const auto nav_data = data_.getNavigationData();
Each of those functions would then require exactly one call to `get<Module>Data` and extract all the information at once. By the way, this also ensures that the data within a certain section does not get out of sync due to multiple calls (in between which changes may occur).

2021-11-26 12:41 UTC, adenhaus commented on src/telemetry/writer.cpp
> +  endList();
@MiltFra this `add` overload packs the minimum and maximum values, and the unit. Not sure what the purpose of this is... but it definitely seems unnecessary to send it every time, as they're constants. Some in `crucialData` are in the same format, I assume the min and max values are helpful for visualising the data. Would it make sense to send these values just once at the beginning instead?

2021-11-26 13:03 UTC, MiltFra commented on src/telemetry/writer.cpp
> +  endList();
Yes, I agree with that.

2021-12-02 19:08 UTC, weijuinlee approved these changes

2021-12-09 17:04 UTC, MiltFra commented on src/telemetry/sendloop.cpp
>      data::Telemetry telemetry_data = data_.getTelemetryData();
I'd move this inside the if because we don't need it outside.

2021-12-09 17:07 UTC, MiltFra requested changes
Also, why is `num_packages_sent` of type `uint16_t`? I think we can afford to make it 32 bits; better safe than sorry.

2021-12-09 17:07 UTC, MiltFra commented on src/telemetry/writer.cpp
> +void Writer::packBattery(std::string name, data::BatteryData battery)
`const` and references please

2021-12-09 17:07 UTC, MiltFra commented on src/telemetry/writer.hpp
>    void packId(uint16_t id);
`const`

2021-12-09 17:07 UTC, MiltFra commented on src/telemetry/writer.hpp
>    void startList(const std::string name);
reference

2022-01-24 11:16 UTC, SnickeyX commented on src/telemetry/writer.cpp
> +  json_writer_.Int(battery.voltage);
If this is intentional then it's perfectly fine, but both voltage and current are logged twice here?

2022-01-24 11:18 UTC, SnickeyX commented on src/telemetry/writer.cpp
> +  json_writer_.Key("current");
If this is intentional this it's perfectly fine, but voltage and current are logged twice?

2022-01-24 18:41 UTC, adenhaus commented on src/telemetry/writer.cpp
> +  json_writer_.Key("current");
Cheers that's what happens when you copy paste code, kids

2022-01-27 17:09 UTC, weijuinlee approved these changes

2022-01-28 07:28 UTC, MiltFra requested changes

2022-01-28 07:28 UTC, MiltFra commented on src/telemetry/sender.cpp
> +      writer.packTime();
Why is this inside the `if`?

2022-01-28 07:28 UTC, MiltFra commented on src/telemetry/writer.cpp
> +void Writer::packBattery(std::string name, const data::BatteryData &battery)
`const std::string &name`? Try if that works with your current code, otherwise don't change this.

2022-01-28 09:39 UTC, adenhaus commented on src/telemetry/sender.cpp
> +      writer.packTime();
Think I misunderstood one of your previous comments. Did you want `data::Telemetry telemetry_data = data_.getTelemetryData();` inside the `if`?

2022-01-28 09:43 UTC, MiltFra commented on src/telemetry/sender.cpp
> +      writer.packTime();
What we want is `data_.getTelemetryData()` before the packing, but outside the `if`. As far as I can tell the `if` only checks for errors.

2022-01-28 09:59 UTC, adenhaus commented on src/telemetry/sendloop.cpp
>      data::Telemetry telemetry_data = data_.getTelemetryData();
@MiltFra see here

2022-01-28 10:01 UTC, adenhaus commented on src/telemetry/sender.cpp
> +      writer.packTime();
Yeah but `getTelemetryData()` is only called so we can set `ModuleStatus` to `kCriticalFailure` if there is an error, so it can probably go inside the `if` which is what I think you were asking for.

2022-01-28 10:04 UTC, adenhaus commented
I've written a test file but the headers have red squiggles under, `cannot open source file "telemetry/writer.hpp"` etc. Tried building it but still same issue. What do I need to do to make it find the headers?

2022-01-28 17:09 UTC, adenhaus commented
> I've written a test file but the headers have red squiggles under, `cannot open source file "telemetry/writer.hpp"` etc. Tried building it but still same issue. What do I need to do to make it find the headers?

@MiltFra

2022-01-28 17:36 UTC, MiltFra commented on src/telemetry/sender.cpp
> +      writer.packTime();
Oh, you're absolutely right. You should move `getTelemetryData` inside and leave the packing outside if I'm not mistaken.

2022-01-28 17:37 UTC, MiltFra commented
> > I've written a test file but the headers have red squiggles under, `cannot open source file "telemetry/writer.hpp"` etc. Tried building it but still same issue. What do I need to do to make it find the headers?
> 
> @MiltFra

Does it compile? try `<telemetry/writer.hpp>` instead.

2022-01-28 18:39 UTC, adenhaus commented
> > > I've written a test file but the headers have red squiggles under, `cannot open source file "telemetry/writer.hpp"` etc. Tried building it but still same issue. What do I need to do to make it find the headers?
> > 
> > 
> > @MiltFra
> 
> Does it compile? try `<telemetry/writer.hpp>` instead.

Yeah I tried `<>` instead of `""`, no difference. Yes it complies. Maybe it's just Intellisense? I'll push so you can check

2022-01-29 16:58 UTC, MiltFra commented on test/telemetry/writer_pack_data_test.cpp
> +TEST_F(WriterPackData, packsNavigationData)
I'd just stick to `WriterTest` to be in line with other test files.

2022-01-29 17:26 UTC, adenhaus commented on test/telemetry/writer_pack_data_test.cpp
> +TEST_F(WriterPackData, packsNavigationData)
That's not how it is in the other telemetry tests, shall I change them all?

2022-01-29 17:28 UTC, adenhaus commented
@MiltFra I need to pass `data` to `Writer` but not sure how to get it in the file. In other files like `sender.cpp` it's being done in the constructor. How do I go about that? (`Writer` takes `data::Data` in its constructor)

2022-01-30 16:53 UTC, MiltFra commented
> @MiltFra I need to pass `data` to `Writer` but not sure how to get it in the file. In other files like `sender.cpp` it's being done in the constructor. How do I go about that? (`Writer` takes `data::Data` in its constructor)

I don't think there's any point in doing that. Just remove it from the constructor and initialise the field with `data::Data::getInstance()`.

2022-01-30 17:15 UTC, adenhaus commented on test/telemetry/writer_pack_data_test.cpp
> +TEST_F(WriterPackData, packsNavigationData)
@MiltFra

2022-01-30 17:23 UTC, adenhaus commented
> > @MiltFra I need to pass `data` to `Writer` but not sure how to get it in the file. In other files like `sender.cpp` it's being done in the constructor. How do I go about that? (`Writer` takes `data::Data` in its constructor)
> 
> I don't think there's any point in doing that. Just remove it from the constructor and initialise the field with `data::Data::getInstance()`.

Not sure what you mean. Check if what I've done now is okay: `const auto data_ = &hyped::data::Data::getInstance();` and than passing `*data_` to `Writer`. Or should I just pass `data::Data::getInstance()` to `Writer` every time?

2022-02-01 10:14 UTC, MiltFra commented on test/telemetry/writer_pack_data_test.cpp
> +TEST_F(WriterPackData, packsNavigationData)
Oh, if that's the case then leave it. Also, message me on Slack because I may not see these in time.

2022-02-07 14:02 UTC, MiltFra requested changes

2022-02-07 14:02 UTC, MiltFra commented on test/telemetry/writer_pack_data.test.cpp
> +  const std::string expectedJson = "{\"id\":" + std::to_string(id) + "}";
Also, check this out: https://www.geeksforgeeks.org/raw-string-literal-c/

2022-02-07 14:13 UTC, adenhaus commented on test/telemetry/writer_pack_data.test.cpp
> +  writer.packSensorsData();
Yeah they're only used once, just seemed neater this way.

2022-02-07 14:18 UTC, adenhaus commented on test/telemetry/writer_pack_data.test.cpp
> +  const std::string expectedJson = "{\"id\":" + std::to_string(id) + "}";
I think using escape slashes and not a literal is actually useful here because in the tests, outputs are printed with the escapes. So comparing is a bit easier if they're the same. But I will change it if you think it's better.

2022-02-07 14:45 UTC, MiltFra commented on test/telemetry/writer_pack_data.test.cpp
> +  const std::string expectedJson = "{\"id\":" + std::to_string(id) + "}";
Alright, let's stick with this then.

2022-02-07 14:45 UTC, MiltFra commented on test/telemetry/writer_pack_data.test.cpp
> +  writer.packSensorsData();
Don't think it is though.

2022-02-07 18:14 UTC, MiltFra commented on test/telemetry/writer_pack_data.test.cpp
> +  const std::string actualJson   = writer.getString();
should be `actual_json`

2022-02-08 15:33 UTC, MiltFra requested changes

2022-02-08 15:33 UTC, MiltFra commented on test/telemetry/writer_pack_data.test.cpp
> +using namespace hyped::data;
Just seeing this now...

2022-02-08 15:33 UTC, MiltFra commented on test/telemetry/writer_pack_data.test.cpp
> +Data &data_ = Data::getInstance();
Also, this is dangerous. I believe it works here but the point of `getInstance` in general is to do it after initialisation (i.e. in function calls) not before. Also the naming convention is off in that case. I'd say get a reference locally or at least put it as a protected member in the test fixture structs.

2022-02-08 20:45 UTC, adenhaus commented on test/telemetry/writer_pack_data.test.cpp
> +using namespace hyped::data;
I asked about this last week. What must I do instead?

2022-02-08 20:51 UTC, adenhaus commented on test/telemetry/writer_pack_data.test.cpp
> +using namespace hyped::data;
I think it wants `hyped::telemetry::` is that right?

2022-02-09 08:38 UTC, MiltFra commented on test/telemetry/writer_pack_data.test.cpp
> +  data::Data &data = data::Data::getInstance();
I know this is within the style guide, but I think it's even less clear now. In the `TEST_F` it looks like `data` is a local variable but it isn't. This is because of the missing underscore which we don't use for structs. Why do we not use it for structs? Because typically we use them to hold data. Nothing else. In particular, we don't usually implement methods on them (though C++ allows this, and sometimes it is required). I'd change the test fixture from `struct` to `class` and add the required underscore(s). I know this is a shortcoming in other test files, don't worry. We should fix that.

2022-02-10 07:49 UTC, MiltFra commented on src/telemetry/sender.cpp
>    while (true) {
I keep finding things, sorry. This should be `while (sys.running_)` (or in new terminology `while (sys.isRunning())`, right? Otherwise this thread will hang potentially forever if we never enter a failure state (which we won't because other threads are exiting as intended).

2022-03-24 21:02 UTC, MiltFra requested changes

2022-03-24 21:03 UTC, adenhaus commented on src/telemetry/writer.hpp
>    void packId(int id);
Can I just do `int`?

2022-03-24 21:07 UTC, MiltFra commented on src/telemetry/writer.hpp
>    void packId(int id);
We don't like that because we are working on different architectures so giving the precise size of the type is helpful. I'm fairly confident that `int` will be identical to `int32_t`, but making it explicit is better. Also, I haven't read the standard...

2022-03-24 21:08 UTC, MiltFra commented on src/telemetry/writer.hpp
>    void packId(int id);
Maybe also add a comment saying after how many seconds/minutes/hours/days/years we will overflow.

2022-03-25 01:14 UTC, MiltFra commented on src/telemetry/writer.cpp
> +// years if we send a package every 100ms
Perfect :joy:

2022-03-25 01:15 UTC, MiltFra approved these changes

2022-03-25 11:15 UTC, adenhaus commented on src/telemetry/writer.cpp
> +// years if we send a package every 100ms
; )

2022-03-31 19:47 UTC, arjunnaha approved these changes

2022-03-31 19:52 UTC, merged