counting packages sent
Hyp-ed/hyped-2022 pull request #88
Opened 2021-11-11 18:04 UTC by adenhaus

## Description
Counting json packages sent from client. Intention is to count packages received on base station side as well and make sure they match.

2021-11-11 19:50 UTC, MiltFra commented
Do we want to have this on master?

2021-11-12 09:37 UTC, MiltFra commented
So I've just had a think about this: This is actually a good number to have and to send to the base station. We can combine it with the timestamp into a primary key if we ever want to have a database of all runs and it allows us to add a timestamp the moment we receive it to analyse delays. Timestamps are not guaranteed to be unique, especially if we're dealing in micros or even milis.

2021-11-12 09:39 UTC, MiltFra requested changes

2021-11-12 09:39 UTC, MiltFra commented on src/telemetry/sendloop.cpp
> +    telemetry_data.num_packages_sent += 1;
I'm not sure we should write this to data. This is not useful information to anyone but the writer. Writes to data are much more expensive than local variables (or class members).

2021-11-12 09:41 UTC, MiltFra commented on src/telemetry/sendloop.cpp
> +    // Increment num packages sent
This reminds me of the textbook example of pointless comments. 

[E.g.](https://stackoverflow.blog/2021/07/05/best-practices-for-writing-code-comments/) this is called the "canonical bad example"
```
i = i + 1;         // Add one to i
```

2021-11-14 22:54 UTC, adenhaus commented on src/telemetry/sendloop.cpp
> +    // Increment num packages sent
Lol fair enough

2021-11-14 22:55 UTC, adenhaus commented on src/telemetry/sendloop.cpp
> +    telemetry_data.num_packages_sent += 1;
Okay understood, I'll just pack it in with the json and send it

2021-11-18 11:00 UTC, adenhaus commented
@MiltFra what's the issue with the failing build? Local tests pass.

2021-11-19 09:56 UTC, MiltFra requested changes
Please fix your auto-formatting; you're changing lines without any reason.

2021-11-20 20:49 UTC, adenhaus commented
> Please fix your auto-formatting; you're changing lines without any reason.

2021-11-20 21:45 UTC, MiltFra requested changes

2021-11-20 21:45 UTC, MiltFra commented on src/telemetry/writer.hpp
> +  void packID(uint16_t id);
should be `packId`

2021-11-20 21:45 UTC, MiltFra commented on src/telemetry/writer.cpp
> +void Writer::packID(uint16_t id)
`const`

2021-11-20 21:45 UTC, MiltFra commented on src/telemetry/sendloop.cpp
> +
there's lots of whitespaces around; wondering whether that makes sense? I know you're just fitting your changes into the style that was already there so I suppose it's fine.

2021-11-20 21:45 UTC, MiltFra commented on src/telemetry/sendloop.cpp
> +  uint16_t num_packs_sent = 0;
I'd call it `num_packages_sent` but idk, won't stop me from approving so dw

2021-11-21 20:27 UTC, MiltFra approved these changes

2021-11-22 12:07 UTC, sashank17 approved these changes

2021-11-22 12:10 UTC, adenhaus commented
Hi @MiltFra please merge thanks boss

2021-11-23 09:45 UTC, merged