Replaced default with individual states
Hyp-ed/hyped-2022 pull request #91
Opened 2021-11-12 03:16 UTC by amadrafi

I replaced all the defaults statements but had troubles with the CMake test.

2021-11-12 09:34 UTC, MiltFra requested changes
Looking at the warnings generated by the compiler, I've also realised that we need to move `num_states` out of the enum into a constexpr `kNumStates`. This will require you to touch quite a few files.

2021-11-12 09:34 UTC, MiltFra commented on src/sensors/gpio_manager.cpp
> +        case data::State::kInvalid:      // undefied behaviour, e.g. kInvalid
Remove the `e.g. kInvalid`

2021-11-12 09:34 UTC, MiltFra commented on src/propulsion/main.cpp
> +
Remove the empty line

2021-11-12 09:34 UTC, MiltFra commented on src/navigation/main.cpp
> +
empty line

2021-11-12 09:34 UTC, MiltFra commented on src/navigation/main.cpp
> +      //Default for all the other states
i don't think we need this comment; it only makes sense in this context, i.e. it won't give any insight in the future

2021-11-12 09:34 UTC, MiltFra commented on src/brakes/main.cpp
> +      //Default for all the other states
...

2021-11-13 20:42 UTC, MiltFra requested changes

2021-11-13 20:42 UTC, MiltFra commented on src/brakes/main.cpp
> +        brakes_.module_status = ModuleStatus::kCriticalFailure;
You need to write back to data to set critical failure. Also, I'd assume we want to handle this similarly to `kEmergencyBraking`.

2021-11-13 20:42 UTC, MiltFra commented on src/navigation/main.cpp
> +        break;
We probably don't want to do nothing here. Either we stop navigation to free up processing to make sure we can shut down properly or we keep navigating to keep reporting displacement/velocity/acceleration.

2021-11-18 11:47 UTC, SnickeyX approved these changes

2021-11-19 09:54 UTC, MiltFra approved these changes

2021-11-19 09:54 UTC, merged