STM - addded pre-calibrating as a sub-state
Hyp-ed/hyped-2022 pull request #93
Opened 2021-11-17 17:23 UTC by SnickeyX

## Description
Adds PreCalibrating as a new sub-state which exists between Idle and Calibrating. To transition from Idle to PreCalibrating -> all modules need to be initialised. To transition from PreCalibrating to Calibrating -> the calibrate command must be given. 

## Changes
- State.cpp -> Added the instance of PreCalibrating
- State.hpp-> Defined PreCalibrating as a new state in the macro
- Data,cpp -> Added PreCalibrating as a string in states
- Data.hpp -> Added PreCalibrating in the enum
- run.test.cpp and state.test.cpp -> modified tests to add PreCalibrating

2021-11-18 10:13 UTC, MiltFra requested changes

2021-11-18 10:13 UTC, MiltFra commented on src/state_machine/state.hpp
> +MAKE_STATE(PreCalibrating)  // Sub-state between Idle and Calibrating
Put this between Idle and Calibrating

2021-11-18 10:13 UTC, MiltFra commented on test/state_machine/run.test.cpp
> +    bool has_emergency           = checkEmergency(log_, brakes_data_, nav_data_, batteries_data_,
Lots of consts missing

2021-11-22 11:27 UTC, amadrafi approved these changes

2021-11-23 09:45 UTC, MiltFra requested changes

2021-11-23 09:45 UTC, MiltFra commented on test/state_machine/state.test.cpp
> + * the calibrate command is not received and if every module
This does not rely on the calibrate command at all anymore, does it?

2021-11-25 13:07 UTC, MiltFra approved these changes

2021-11-25 13:07 UTC, merged