Mtc controller config messages
Hyp-ed/hyped-2022 pull request #96
Opened 2021-11-18 15:42 UTC by TomLonergan03

Possible issues with config messages

2021-11-18 15:43 UTC, TomLonergan03 commented on src/propulsion/messages.hpp
> +  {0x2B, 0x40, 0x20, 0x03, 0x01, 0x00, 0x00, 0x00},//n not in manual
this one

2021-11-18 15:43 UTC, TomLonergan03 commented on src/propulsion/messages.hpp
> +  {0x2B, 0xF6, 0x60, 0x02, 0x88, 0x13, 0x00, 0x00},//n sets to 5000
this one

2021-11-18 15:43 UTC, TomLonergan03 commented on src/propulsion/messages.hpp
> +  {0x2B, 0xF6, 0x60, 0x03, 0x80, 0x3E, 0x00, 0x00},//n sets to 16000
this one

2021-11-18 15:43 UTC, TomLonergan03 commented on src/propulsion/messages.hpp
> +  {0x2B, 0xF6, 0x60, 0x04, 0x88, 0x13, 0x00, 0x00},//n sets to 5000
and this one

2021-11-19 10:05 UTC, MiltFra requested changes
Alright, I agree with your observations. 
Please a) write down *all* the variables we need to check and b) talk to propulsion about the intended values. I'm assuming we'll add some human-readable configs for that, but that's yet to be determined.

2021-11-19 10:06 UTC, MiltFra commented
Also, this is just a copy of the cleanup PR, right?

2021-11-19 10:06 UTC, closed without merging