STM - adding PreBraking and Failure PreBraking
Hyp-ed/hyped-2022 pull request #99
Opened 2022-01-09 12:16 UTC by SnickeyX

## Description
Adds the new sub-states of PreBraking and Failure PreBraking. 

## Changes
- data.cpp                 -> added new states to the array 
- data.hpp                 -> added new states to the enum and a boolean to track all SSRs state
- gpio_manager.cpp -> added new  states to the switch statement. setHP and clearHP now help track the state of all SSRs
- state.cpp                -> added PreBraking
- state.hpp                -> added both sub-states
- transitions.[c/h]pp  -> added new function to retrieve SSR state from the CDS
- run.test.cpp            -> added/modified tests to accommodate PreBraking 
- state.test.cpp          -> added/modified tests to accommodate PreBraking + added tests for Cruising 

## Additional Info 
- Still need to fully add Failure PreBraking 
- Accelerating test for reaching maximum velocity keeps failing - need to fix (state.test.cpp)

2022-01-09 13:37 UTC, MiltFra requested changes

2022-01-09 13:37 UTC, MiltFra commented on src/state_machine/transitions.hpp
> +bool checkHPOff(const data::Sensors &sensors_data_struct);
`checkHighPowerOff`

2022-01-09 13:37 UTC, MiltFra commented on src/state_machine/transitions.cpp
> +  if (!sensors_data_struct.HP_off) return false;
While we're at it, please rename this to `high_power_off`.

2022-01-09 13:37 UTC, MiltFra commented on test/state_machine/run.test.cpp
> +    const bool has_hp_off               = checkHPOff(sensors_data_);
`has_high_power_off`

2022-01-09 13:37 UTC, MiltFra commented on test/state_machine/state.test.cpp
> +/**
Commented code?

2022-01-09 13:40 UTC, SnickeyX commented on test/state_machine/state.test.cpp
> +/**
Could not get that test to pass and don't know why. Will try again

2022-01-09 14:24 UTC, MiltFra commented on src/data/data.cpp
> +  "Idle",
Also this auto formatting seems weird?

2022-01-10 19:37 UTC, amadrafi approved these changes

2022-01-10 19:53 UTC, MiltFra commented on src/state_machine/transitions.cpp
> +  if (!sensors_data_struct.HP_off) return false;
it's still `HP_off` here

2022-01-13 12:15 UTC, MiltFra requested changes

2022-01-13 12:15 UTC, MiltFra commented on test/state_machine/state.test.cpp
> -      if (reached_max_velocity) {
I'd rather you made sure this is false by modifying the relevant values in the CDS. This way we may never actually encounter an interesting test case because we're always in the braking zone.

2022-01-13 12:51 UTC, SnickeyX commented on src/state_machine/transitions.cpp
> +  if (!sensors_data_struct.HP_off) return false;
This has been changed

2022-02-03 12:23 UTC, MiltFra reviewed
You'll have to explain to me what you did here and why it's working now before we merge this dangerous piece of code...

2022-02-03 12:23 UTC, MiltFra commented on test/state_machine/state.test.cpp
> +          << "failed to enter Cruising from Accelerating ";
? :eyes:

2022-02-04 16:47 UTC, MiltFra commented on src/data/data.hpp
> +  bool high_power_off = false;  // true if all SSRs are not in HP
I don't like the "double negation" here. Maybe just call it `high_power_active` and reverse the values?

2022-02-04 16:55 UTC, MiltFra commented on src/state_machine/transitions.cpp
> +  if (!sensors_data_struct.high_power_off) return false;
`return sensors_data_struct.high_power_off;`

That is unless you want to log something here like we are in other places? That was the main point of these changes anyways.

2022-02-04 16:59 UTC, MiltFra approved these changes

2022-02-04 16:59 UTC, merged